# Generated by Django 4.1.5 on 2023-01-25 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=240, null=True, verbose_name='Alias')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserInfo',
                'verbose_name_plural': 'UserInfos',
            },
        ),
    ]
