# Generated by Django 4.1.5 on 2023-01-30 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_type', models.CharField(max_length=25, null=True)),
                ('user', models.CharField(max_length=240, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GraphMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=240, null=True)),
                ('author', models.CharField(max_length=25, null=True)),
                ('is_start', models.BooleanField(default=False)),
                ('is_end', models.BooleanField(default=False)),
                ('next', models.ManyToManyField(to='app.graphmessage')),
                ('prev', models.ManyToManyField(to='app.graphmessage')),
            ],
        ),
        migrations.CreateModel(
            name='DialogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.dialog')),
            ],
        ),
    ]
