# Generated by Django 4.1.5 on 2023-02-14 20:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_dialog_userinfo_last_bot_message_pk_graphmessage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dialog',
            new_name='History',
        ),
    ]
