# Generated by Django 4.1.5 on 2023-02-14 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_dialog_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DialogMessage',
            new_name='HistoryMessage',
        ),
    ]
