# Generated by Django 4.1.5 on 2023-02-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_dialog_historymessage_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='dialog_style',
            field=models.CharField(max_length=60, null=True, verbose_name='Alias'),
        ),
    ]
