# Generated by Django 4.1.5 on 2023-02-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userinfo_dialog_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='alias',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(max_length=240, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='dialog_style',
            field=models.CharField(max_length=60, null=True, verbose_name='Dialog Style'),
        ),
    ]
