# Generated by Django 4.1.5 on 2023-02-21 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_userinfo_completed_survey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphmessage',
            options={'verbose_name': 'GraphMessage', 'verbose_name_plural': 'GraphMessages'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'History', 'verbose_name_plural': 'Histories'},
        ),
        migrations.AlterModelOptions(
            name='historymessage',
            options={'verbose_name': 'HistoryMessage', 'verbose_name_plural': 'HistoryMessages'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='invited_by',
            field=models.ManyToManyField(blank=True, related_name='invited_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
