# Generated by Django 4.1.5 on 2023-02-21 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_remove_userinfo_invited_userinfo_invited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='invited_by',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited', to=settings.AUTH_USER_MODEL),
        ),
    ]
