# Generated by Django 4.1.5 on 2023-02-21 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_remove_userinfo_invited_by_userinfo_invited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='invited_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited', to=settings.AUTH_USER_MODEL),
        ),
    ]
