# Generated by Django 4.1.5 on 2023-02-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_userinfo_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='completed_dialog',
            field=models.CharField(max_length=60, null=True, verbose_name='Dialog Style'),
        ),
    ]
