# Generated by Django 4.1.5 on 2023-02-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_userinfo_completed_dialog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='completed_dialog',
            field=models.BooleanField(default=False, verbose_name='Completed Dialog'),
        ),
    ]
