# Generated by Django 4.1.5 on 2023-02-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_userinfo_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='verification_code',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Verification Code'),
        ),
    ]
