# Generated by Django 4.1.5 on 2023-02-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_userinfo_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='bot_type',
        ),
    ]
