# Generated by Django 4.1.5 on 2023-03-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_graphmessage_one_on_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='completed_survey',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='completed_survey_part1',
            field=models.BooleanField(default=False, verbose_name='Survey Part 1'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='completed_survey_part2',
            field=models.BooleanField(default=False, verbose_name='Survey Part 2'),
        ),
    ]
