# Generated by Django 4.1.5 on 2023-03-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_userinfo_completed_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphmessage',
            name='explore_siblings',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Min explored sibling paths'),
        ),
    ]
