# Generated by Django 4.1.5 on 2023-03-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_graphmessage_explore_siblings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphmessage',
            name='content',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
