# Generated by Django 4.1.5 on 2023-03-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_graphmessage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='verified',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='rushed',
            field=models.BooleanField(default=False, verbose_name='Rushed (through interaction)'),
        ),
    ]
